### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by pirey** [zackiles/elasticsearch-odm#24]
I just trying out the example directly from README
```
var elasticsearch = require('elasticsearch-odm')
var Car = elasticsearch.model('Car')
var car = new Car({
  type: 'Ford', color: 'Black'
})
elasticsearch.connect('my-index').then(function () {
  // be sure to call connect before bootstrapping your app.
  car.save().then(function (document) {
    console.log(document)
  })
}).catch(e => {
  console.log('Error: ', e)
})
```

and that gives me this

```
Unhandled rejection Error: Bad Request
    at respond (/Users/yeri/dev/chatio/node_modules/elasticsearch-odm/node_modules/elasticsearch/src/lib/transport.js:238:15)
    at checkRespForFailure (/Users/yeri/dev/chatio/node_modules/elasticsearch-odm/node_modules/elasticsearch/src/lib/transport.js:201:7)
    at HttpConnector.<anonymous> (/Users/yeri/dev/chatio/node_modules/elasticsearch-odm/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/yeri/dev/chatio/node_modules/elasticsearch-odm/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

I'm using node v.6.9.4 on mac

**Comment by bloublou2014** [comment]
What is your version of Elasticsearch ?

If you are using 1.x/2.0 (what i doubt nowdays) you can still use this repository.
If you are using Elasticsearch 2.x you can try using elasticsearch-odm-2
If you are using Elasticsearch 5.x you can try using elasticsearch-odm-5
It's a forked of zackiles with some adaptation to work with elasticsearch 2 or 5.

Seems Epsilonn2/elasticsearch-odm is also updated frequently and support es5.x

Try again with one of this fork.
